server:
  port: 8081

spring:
  application:
    name: game-platform-api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: main-page-service
              uri: http://main-page-service:8082
              predicates:
                - Path=/api/v1/**
              filters:
                - RemoveRequestHeader=X-User-Id
                - RemoveRequestHeader=X-User-Roles
                - RemoveRequestHeader=X-Request-Id

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/game-realm

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always